# Generated by Django 3.2.18 on 2023-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230510_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
