# Generated by Django 3.2.19 on 2023-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cartproduct_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productimage',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
